/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:b77c5782-572a-4fc3-9968-086763092ced",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_jxZJ9jTWY",
    "aws_user_pools_web_client_id": "74ap671kqoqfc0n4r8h63jdb8u",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "vpastaticsbucket214516-dev",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;